name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: clojure:openjdk-17-tools-deps-slim-bullseye

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Cache mvn/git deps
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            /root/.gitlibs
            /root/.m2
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}

      - name: Lint
        run: clojure -T:project lint

      - name: Format
        run: clojure -T:project format-check

      - name: Test
        id: test
        run: clojure -T:project test :kaocha.filter/focus '[:unit]'

      - name: Run tests
        run: clj -X:test
